"use strict";

/** Mongoose default collection names and schema field names (including __v, timestamps). */
const EXPECTED = {
  users: {
    fields: [
      "_id",
      "username",
      "email",
      "phone",
      "password",
      "sessionToken",
      "tokenVersion",
      "hasUsedTrial",
      "trialGrantedAt",
      "deviceId",
      "lastRegisterIP",
      "lastDeviceId",
      "deviceSwitchWindowStart",
      "deviceSwitchCount",
      "deviceSwitchFirstAt",
      "lockUntil",
      "lockReason",
      "role",
      "isActive",
      "blocked",
      "isVIP",
      "vipExpiresAt",
      "vipLevel",
      "avatar",
      "resetPasswordTokenHash",
      "resetPasswordExpiresAt",
      "resetPasswordRequestedAt",
      "bookmarks",
      "recentlyViewed",
      "createdAt",
      "updatedAt",
      "__v",
    ],
    nested: {
      bookmarks: ["manhua", "addedAt", "_id"],
      recentlyViewed: ["manhua", "lastChapter", "lastReadAt", "_id"],
    },
  },
  manhuas: {
    fields: [
      "_id",
      "title",
      "titleEn",
      "slug",
      "rating",
      "description",
      "coverImage",
      "coverImageUrl",
      "ratingAverage",
      "ratingCount",
      "status",
      "genres",
      "createdBy",
      "owners",
      "team",
      "views",
      "dailyViews",
      "weeklyViews",
      "deletedAt",
      "deletedBy",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  chapters: {
    fields: [
      "_id",
      "manhua",
      "chapterNumber",
      "title",
      "pages",
      "language",
      "status",
      "views",
      "dailyViews",
      "monthlyViews",
      "uploadedBy",
      "deletedAt",
      "deletedBy",
      "createdAt",
      "updatedAt",
      "__v",
    ],
    nested: {
      pages: ["pageNumber", "imageUrl", "originalName", "width", "height", "sourceUrl"],
    },
  },
  teams: {
    fields: ["_id", "name", "description", "createdBy", "members", "createdAt", "updatedAt", "__v"],
    nested: {
      members: ["user", "role", "addedBy", "addedAt"],
    },
  },
  teaminvites: {
    fields: [
      "_id",
      "team",
      "invitedUser",
      "invitedBy",
      "role",
      "status",
      "respondedAt",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  comments: {
    fields: ["_id", "user", "username", "chapter", "manhua", "text", "createdAt", "updatedAt", "__v"],
  },
  favorites: {
    fields: ["_id", "user", "manhua", "createdAt", "updatedAt", "__v"],
  },
  bookmarks: {
    fields: ["_id", "user", "manhua", "chapterNumber", "pageNumber", "createdAt", "updatedAt", "__v"],
  },
  requests: {
    fields: [
      "_id",
      "title",
      "imageUrl",
      "createdBy",
      "votes",
      "monthlyVotes",
      "votersByMonth",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  feedbacks: {
    fields: ["_id", "type", "name", "description", "imageUrl", "status", "createdAt", "updatedAt", "__v"],
  },
  vipplans: {
    fields: ["_id", "months", "priceTotal", "active", "displayOrder", "createdAt", "updatedAt", "__v"],
  },
  trialdevices: {
    fields: ["_id", "deviceId", "firstUserId", "firstGrantedAt", "ip", "createdAt", "updatedAt", "__v"],
  },
  appsettings: {
    fields: ["_id", "key", "value", "createdAt", "updatedAt", "__v"],
  },
  financemonths: {
    fields: [
      "_id",
      "monthKey",
      "totalRevenue",
      "currency",
      "revenueEvents",
      "createdAt",
      "updatedAt",
      "__v",
    ],
    nested: {
      revenueEvents: ["userId", "adminId", "amount", "currency", "paidAt", "monthsGranted", "note"],
    },
  },
  editormonthstats: {
    fields: [
      "_id",
      "monthKey",
      "editorId",
      "chapterMonthlyViews",
      "chaptersUploaded",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  editormanhuamonthstats: {
    fields: [
      "_id",
      "monthKey",
      "editorId",
      "manhuaId",
      "monthlyViews",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  chapterreads: {
    fields: ["_id", "chapterId", "viewerKey", "firstReadAt", "createdAt", "updatedAt", "__v"],
  },
  chapterreadmonths: {
    fields: [
      "_id",
      "chapterId",
      "viewerKey",
      "monthKey",
      "firstReadAt",
      "expireAt",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  auditlogs: {
    fields: [
      "_id",
      "ts",
      "level",
      "category",
      "action",
      "message",
      "user",
      "ip",
      "deviceIdHash",
      "method",
      "path",
      "statusCode",
      "durationMs",
      "requestId",
      "meta",
    ],
    nested: {
      user: ["id", "username", "role"],
    },
  },
  actionlogs: {
    fields: [
      "_id",
      "user",
      "action",
      "targetType",
      "targetId",
      "description",
      "createdAt",
      "updatedAt",
      "__v",
    ],
  },
  registerattempts: {
    fields: ["_id", "ip", "createdAt", "updatedAt", "__v"],
  },
};

module.exports = { EXPECTED };
